openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/register:
    post:
      summary: ''
      operationId: postApiRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: ab
                  nullable: false
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: idell.jones@example.org
                  nullable: false
                password:
                  type: string
                  description: ''
                  example: non
                  nullable: false
                confirm_password:
                  type: string
                  description: 'The value and <code>password</code> must match.'
                  example: consequatur
                  nullable: false
              required:
                - name
                - email
                - password
                - confirm_password
      security: []
  /api/login:
    post:
      summary: 'Login api'
      operationId: loginApi
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/test:
    post:
      summary: ''
      operationId: postApiTest
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
